### ISSUE TITLE
Create directories for calculator and gui

### ISSUE THREAD

**Issue by belisama** [belisama/drakor-patterns#18]

**Comment by belisama** [comment]
Or institute naming standard. Consider while completing multi-file branch (don't do both at same time, would be merge mess!).

**Comment by Bl00D4NGEL** [comment]
I think the document names for the gui things should be: "gui_tradeskill"
The other part could be called "tree_tradeskill" or "patterns_tradeskill"
Whereas I'd prefer "tree_tradeskill" over the other one as "tree" is by far more indicating for me than "patterns"
